### ISSUE TITLE
Minor Grammatical Issues in Repopack Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by Mefisto04** [yamadashy/repopack#106]
This pull request addresses a couple of minor grammatical issues found in the **Repopack Contributor Covenant Code of Conduct**. These changes aim to enhance the clarity and readability of the document, ensuring that the language is accurate and consistent.

### Changes Made:
1. **Verb Correction**  
2. **Clarification in "Examples of Unacceptable Behavior"**  

---

### Examples:
1. **Before the fix (Pledge Section)**:
2. **Before the fix (Unacceptable Behavior Section)**:  
3. and many more...

**Comment by yamadashy** [comment]
@Mefisto04 

Thank you for addressing these grammatical issues. Your comment mentions "This pull request addresses...", but I'm not able to see the associated pull request. Has a PR been created for these changes? If so, could you please provide a link to it?

If a PR hasn't been created yet, it would be helpful if you could submit one with your proposed modifications so we can review the specific changes.

Thanks for your contribution to improving the project documentation!

**Comment by Mefisto04** [comment]
hey @yamadashy , you can assign this issue to me, after that i can make changes and make a pull request as well, I have done necessary changes just waiting for your assign.

**Comment by Mefisto04** [comment]
#109

**Comment by yamadashy** [comment]
I've merged the PR #109 which addresses the updates to the Contributor Covenant Code of Conduct. As this resolves all the concerns raised in this issue, I'm going to close it now.

Thank you for your valuable contribution to this issue!
