### ISSUE TITLE
Refactor: Centralize renderContext & style generation logic for output styles

### ISSUE THREAD

**Issue by iNerdStack** [yamadashy/repopack#125]
The renderContext was repeated in all three style generation files including the logic to generate
 
<code>/src/core/output/outputStyles/plainStyle.ts</code>
<code>/src/core/output/outputStyles/xmlStyle.ts</code>
<code>/src/core/output/outputStyles/markdownStyle.ts</code>

``` javascript
export const generateMarkdownStyle = (outputGeneratorContext: OutputGeneratorContext) => {
  const template = Handlebars.compile(markdownTemplate);

  const renderContext = {
    generationHeader: generateHeader(outputGeneratorContext.generationDate),
    summaryPurpose: generateSummaryPurpose(),
    summaryFileFormat: generateSummaryFileFormat(),
    summaryUsageGuidelines: generateSummaryUsageGuidelines(
      outputGeneratorContext.config,
      outputGeneratorContext.instruction,
    ),
    summaryNotes: generateSummaryNotes(outputGeneratorContext.config),
    summaryAdditionalInfo: generateSummaryAdditionalInfo(),
    headerText: outputGeneratorContext.config.output.headerText,
    instruction: outputGeneratorContext.instruction,
    treeString: outputGeneratorContext.treeString,
    processedFiles: outputGeneratorContext.processedFiles,
  };

  return `${template(renderContext).trim()}\n`;
};
```

###  Proposed Solution
Move the common logic in these files into a shared utility file. This will make it easier to maintain as you add new styles and also add new parameters for renderContext in the future

**Comment by yamadashy** [comment]
@iNerdStack 
You're absolutely right!

Now that you mention it, it does make sense. It seems like a good approach to place a method for creating the renderContext in outputGenerate, and then pass this renderContext to each generate method. Taking it a step further, we could even consider having xmlStyle.ts and others just return the template, and then do the actual rendering in outputGenerate.

Thanks for bringing this to my attention!

**Comment by iNerdStack** [comment]
Exactly, that's what I was thinking too. Can you assign me to this, and I can make a proposed PR or can you work that out?

**Comment by yamadashy** [comment]
@iNerdStack 
If you have the time, I’d really appreciate it! Thank you, I’ll go ahead and assign this to you.

**Comment by yamadashy** [comment]
I realized that caching the compiled templates could lead to further optimization, so I've created a PR for this.

- https://github.com/yamadashy/repopack/pull/130

**Comment by yamadashy** [comment]
I really appreciate your work on this. I'll go ahead and close this issue now. 

Please don't hesitate to reach out if you have any more ideas or suggestions in the future!
