### ISSUE TITLE
Broken link (LICENSE) in README

### ISSUE THREAD

**Issue by Kaushik080** [yamadashy/repopack#140]
Current Behavior:
LICENSE in README redirects to invalid link ( 404 )

Expected Behavior:
It should redirect to correct link
![image](https://github.com/user-attachments/assets/e7b8a3f0-3114-42e0-8dcd-27e0b8916c88)
![image](https://github.com/user-attachments/assets/d909ec95-3bac-4f0d-9099-e9e9284cdb7f)

**Comment by yamadashy** [comment]
Thank you for reporting and fixing this issue with a clear explanation @Kaushik080!

Feel free to share any other feedback or suggestions you might have for the project. Your contributions are welcome!
