### ISSUE TITLE
feat: add `include` filters

### ISSUE THREAD

**Issue by pakrentos** [yamadashy/repopack#22]
Though `ignore` filters are useful, it would be helpful to have the opposite. For example pack only "*.md" files

**Comment by yamadashy** [comment]
Thank you for your feedback! That's a great idea.

While it might be good to have include and exclude patterns like in tsconfig, for repopack, I think we'll keep the existing ignore functionality and add include as a new feature.

I imagine the config would look something like this:

```json5
{
  "output": {
    ...
  },
  "include": ["*.ts", "*.md"],
  "ignore": {
    ...
  }
}
```

For the CLI, it would be nice if we could use it like this:
```
repopack --include "src/**/*.ts,*.md"
```

What do you think about this approach? Does this align with what you had in mind?

**Comment by IsaacSante** [comment]
Hey this would be great. I actually tried to fork the repo to make this feature. I was filtering the paths in getPaths before the security check was done and returning only the files in the --include flag. I think the main thing for this feature at least for me is I want to be able to pass in specific files in my repo that I want packed in the output file. For example if im working on a feature there might be 2-5 files in my entire repo that are relevant to that feature. Including all of the files in the repo for the llm is still to much for the context window to handle and give back specific answers at least in chatgpt 4.

**Comment by IsaacSante** [comment]
Curious to see how you would implement this though and thanks for your work on this tool has been super helpful.

**Comment by IsaacSante** [comment]
Here's a general idea of what I had sketched out in case it helps at all. 

## CLI Usage

The CLI command allows specifying the files to include using relative paths, separated by spaces:

```sh
repopack --include /src/index.ts /src/utils/logger.ts /package.json
```

## Implementation Details

### `Cli/Index.ts`

Defines the CLI options and arguments, including the `--include` option for specifying files to be included:

```typescript
interface CliOptions extends OptionValues {
  version?: boolean;
  output?: string;
  ignore?: string;
  config?: string;
  verbose?: boolean;
  topFilesLen?: number;
  outputShowLineNumbers?: boolean;
  include?: string[];
}

// CLI setup
program
  .version(version)
  .description('Repopack - Pack your repository into a single AI-friendly file')
  .arguments('[directory]')
  .option('-v, --version', 'show version information')
  .option('-o, --output <file>', 'specify the output file name')
  .option('-i, --ignore <patterns>', 'additional ignore patterns (comma-separated)')
  .option('-c, --config <path>', 'path to a custom config file')
  .option('--top-files-len <number>', 'specify the number of top files to display', parseInt)
  .option('--output-show-line-numbers', 'add line numbers to each line in the output')
  .option('--include <files...>', 'space-separated list of files to include')      
  .option('--verbose', 'enable verbose logging for detailed output')
  .action((directory = '.', options: CliOptions) => executeAction(directory, options));
```

### `Packager.ts`

Handles file filtering based on the `include` option and processes the files accordingly:

```typescript
const ignorePatterns = await deps.getAllIgnorePatterns(rootDir, config);
const ignoreFilter = deps.createIgnoreFilter(ignorePatterns);

// Get all file paths in the directory
const filePaths = await getFilePaths(rootDir, '', ignoreFilter);
const filteredPaths = filterIncludedFiles(rootDir, filePaths, config.include);

// Use filteredPaths if not empty, otherwise use filePaths
const pathsToProcess = filteredPaths.length > 0 ? filteredPaths : filePaths;
// Perform security check
const suspiciousFilesResults = await performSecurityCheck(pathsToProcess, rootDir);

// Pack files and generate output
const packedFiles = await packFiles(pathsToProcess, rootDir, config, deps);
await deps.generateOutput(rootDir, config, packedFiles);
```

### `Utils/includeUtils.ts`

Defines the utility function for filtering files based on the `include` list:

```typescript
import path from 'path';
import { logger } from '../utils/logger.js';

export function filterIncludedFiles(rootDir: string, filePaths: string[], include: string[]): string[] {
  if (include.length === 0) {
    return filePaths;
  }

  // Normalize paths to handle case insensitivity and different representations
  const normalizePath = (p: string) => path.normalize(path.resolve(rootDir, p)).toLowerCase();

  // Create a Set of normalized absolute paths for the included files
  const includeSet = new Set(include.map(normalizePath));

  // Map file paths to their normalized absolute paths and filter those that are in the include set
  const filteredAbsolutePaths = filePaths
    .map(filePath => path.resolve(rootDir, filePath))
    .filter(absolutePath => includeSet.has(normalizePath(absolutePath)));

  // Log any files in includeSet that are not found in filePaths
  const absoluteFilePathsSet = new Set(filePaths.map(filePath => normalizePath(path.resolve(rootDir, filePath))));
  // [additional logic to handle unmatched include files]
}
```

**Comment by yamadashy** [comment]
@IsaacSante 
Hi,
Thank you so much for your valuable contribution and for taking the time to work on this feature! 

Your approach looks promising, and I'd love to see it integrated into the project. Would you be willing to create a pull request with your changes? This would allow us to review the code together, discuss any potential adjustments, and eventually merge it into the main branch.

Your current implementation with file-specific includes is a great start. As a future enhancement, i’ll support glob patterns for more flexible file matching, but let's begin with your current version and iterate from there.

Once again, thank you for your contribution. I'm looking forward to your pull request and continuing to improve Repopack together!

**Comment by yamadashy** [comment]
@IsaacSante 
I'll merge this branch into my branch and test it out. Then I'll add the glob pattern implementation and release it!
The base code you provided is really helpful! Thank you!
https://github.com/IsaacSante/repopack/compare/IsaacSante:repopack:main...includefiles

**Comment by yamadashy** [comment]
@IsaacSante 

I've made significant changes to the implementation to support glob patterns, but your initial work was incredibly helpful.

Regarding the CLI specification for include patterns, we decided to use comma-separated values, similar to the ignore option. This decision was made after careful consideration, as it helps avoid ambiguity with direct `path/to/directory` inputs and maintains consistency across the CLI interface.

The implementation is now complete, and we're planning to release it soon. Your contribution has been invaluable, and we truly appreciate your input.

You can find the details of the changes in this PR:
- https://github.com/yamadashy/repopack/pull/30

Thank you again for your contribution!

**Comment by yamadashy** [comment]
I'm pleased to inform you that we've released the new version with the include functionality:

https://github.com/yamadashy/repopack/releases/tag/v0.1.19

If you have any feedback after trying it out, I'd be very grateful to hear your thoughts.

**Comment by IsaacSante** [comment]
Hey was working yesterday didn't see your message but happy to hear it was helpful will be trying out this feature for sure. Thanks !

**Comment by yamadashy** [comment]
This is fantastic, thanks again for all your help getting this feature released!

**Comment by yamadashy** [comment]
Thank you for your valuable contribution and the time you've invested in improving Repopack!
I'll closing this issue.
