### ISSUE TITLE
Honour .gitignore in subfolders as well

### ISSUE THREAD

**Issue by codevalley** [yamadashy/repopack#34]
Seems like the script is only looking into a global gitignore (on root folder), but if there are specific gitignore files in the subfolders they're ignored.

**Comment by yamadashy** [comment]
Thank you for bringing this to my attention!

You're absolutely right. We indeed overlooked the .gitignore files in subdirectories.

I'll work on implementing a fix for this issue. 

Thank you again for your valuable feedback.

**Comment by yamadashy** [comment]
Thank you for reporting this issue. We've addressed it in the following pull request:
- https://github.com/yamadashy/repopack/pull/35

The fix has been merged and released in [v0.1.21](https://github.com/yamadashy/repopack/releases/tag/v0.1.21)

Please update to the latest version and let us know if you encounter any further issues or if this doesn't fully resolve your concern.

We appreciate your contribution to improving Repopack!

**Comment by yamadashy** [comment]
I'll closing this issue. Thank you for improvement of Repopack.
As always, I welcome any further suggestions or comments to improve Repopack!
