### ISSUE TITLE
exclude packager lock file by default

### ISSUE THREAD

**Issue by gengjiawen** [yamadashy/repopack#90]
npm: package-lock.json
Yarn: yarn.lock
pnpm: pnpm-lock.yaml

**Comment by yamadashy** [comment]
Thank you for bringing this to our attention!

We are already ignoring these files by default. You can see the implementation here:
https://github.com/yamadashy/repopack/blob/main/src/config/defaultIgnore.ts#L109-L111

Please let us know if you're encountering a situation where these files are not being ignored as expected. We'd be happy to investigate further if needed.

**Comment by gengjiawen** [comment]
> Thank you for bringing this to our attention!
> 
> We are already ignoring these files by default. You can see the implementation here: [`main`/src/config/defaultIgnore.ts#L109-L111](https://github.com/yamadashy/repopack/blob/main/src/config/defaultIgnore.ts?rgh-link-date=2024-09-29T15%3A11%3A01Z#L109-L111)
> 
> Please let us know if you're encountering a situation where these files are not being ignored as expected. We'd be happy to investigate further if needed.

It's in subfolder. like https://github.com/gengjiawen/buffett-chinese/blob/main/crawler/yarn.lock.

**Comment by yamadashy** [comment]
Thank you!

I've addressed this issue in our latest release, version 0.1.40. The update now properly excludes lock files in subdirectories as well.

https://github.com/yamadashy/repopack/releases/tag/v0.1.40

Please check it out and let us know if it resolves the issue you were experiencing.

**Comment by yamadashy** [comment]
@gengjiawen Hi!
Just a friendly reminder about the lock file exclusion update in version 0.1.40. Have you had a chance to try it out? We'd love to hear if it resolved the issue for you. Thanks!

**Comment by gengjiawen** [comment]
works really good. thx.
